sonar.projectKey=AnderssonProgramming_digital-wellbeing-cloud-architecture
sonar.organization=anderssonprogramming
sonar.sources=services/rule-engine/rule_engine,services/normalizer/normalizer,services/anonymizer/anonymizer,services/inference-svc/inference_svc,ml
sonar.tests=services/rule-engine/tests,services/normalizer/tests,services/anonymizer/tests,services/inference-svc/tests,ml/tests
sonar.python.coverage.reportPaths=services/*/coverage.xml
sonar.python.version=3.11
sonar.qualitygate.wait=true
