apiVersion: v1
kind: Namespace
metadata:
  name: ns-ingestion
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-processing
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-data-ml
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-staging
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-test
