apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  APP_NAME: {{ .Chart.Name | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | default "INFO" | quote }}
  INFLUXDB_URL: {{ .Values.env.INFLUXDB_URL | default "" | quote }}
