apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  APP_NAME: {{ .Chart.Name | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | default "INFO" | quote }}
  SCHEMA_REGISTRY_URL: {{ .Values.env.SCHEMA_REGISTRY_URL | default "" | quote }}
