image:
  repository: kong
  tag: "3.6"
  pullPolicy: IfNotPresent

env:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_LOG_LEVEL: info

service:
  type: LoadBalancer
  ports:
    proxy: 80
    admin: 8001

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
